version: '3'
services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend_react
    ports:
      - '80:3000'
    links:
      - backend
  backend:
    container_name: backend
    restart: always
    build: ./backend-express
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.0-bionic
    ports:
      - '27017:27017'
