version: "3"
services:  
  app:
    image: node:10.16.3-alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 3000:3000
    command: npm run dev  
  
  mongo:
    image: mongo:4.2.0-bionic
    ports:
      - 27017:27017
    volumes:
      - ~/data/db:/data/db